//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employees.Employees {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        private int departmentField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Name1Field;
        
        private int Department1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int department {
            get {
                return this.departmentField;
            }
            set {
                if ((this.departmentField.Equals(value) != true)) {
                    this.departmentField = value;
                    this.RaisePropertyChanged("department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Name", EmitDefaultValue=false, Order=3)]
        public string Name1 {
            get {
                return this.Name1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Name1Field, value) != true)) {
                    this.Name1Field = value;
                    this.RaisePropertyChanged("Name1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Department", IsRequired=true, Order=4)]
        public int Department1 {
            get {
                return this.Department1Field;
            }
            set {
                if ((this.Department1Field.Equals(value) != true)) {
                    this.Department1Field = value;
                    this.RaisePropertyChanged("Department1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Department : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int EmpCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int EmpCount {
            get {
                return this.EmpCountField;
            }
            set {
                if ((this.EmpCountField.Equals(value) != true)) {
                    this.EmpCountField = value;
                    this.RaisePropertyChanged("EmpCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Employees.Employees_serviceSoap")]
    public interface Employees_serviceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        void Add();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task AddAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit", ReplyAction="*")]
        void Edit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit", ReplyAction="*")]
        System.Threading.Tasks.Task EditAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove", ReplyAction="*")]
        void Remove();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove", ReplyAction="*")]
        System.Threading.Tasks.Task RemoveAsync();
        
        // CODEGEN: Контракт генерации сообщений с именем GetEmployeeResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployee", ReplyAction="*")]
        Employees.Employees.GetEmployeeResponse GetEmployee(Employees.Employees.GetEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<Employees.Employees.GetEmployeeResponse> GetEmployeeAsync(Employees.Employees.GetEmployeeRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetDepartmentResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartment", ReplyAction="*")]
        Employees.Employees.GetDepartmentResponse GetDepartment(Employees.Employees.GetDepartmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartment", ReplyAction="*")]
        System.Threading.Tasks.Task<Employees.Employees.GetDepartmentResponse> GetDepartmentAsync(Employees.Employees.GetDepartmentRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetEmployeesResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        Employees.Employees.GetEmployeesResponse GetEmployees(Employees.Employees.GetEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<Employees.Employees.GetEmployeesResponse> GetEmployeesAsync(Employees.Employees.GetEmployeesRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetDepartmentsResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartments", ReplyAction="*")]
        Employees.Employees.GetDepartmentsResponse GetDepartments(Employees.Employees.GetDepartmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartments", ReplyAction="*")]
        System.Threading.Tasks.Task<Employees.Employees.GetDepartmentsResponse> GetDepartmentsAsync(Employees.Employees.GetDepartmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Choosing", ReplyAction="*")]
        void Choosing();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Choosing", ReplyAction="*")]
        System.Threading.Tasks.Task ChoosingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save", ReplyAction="*")]
        void Save();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save", ReplyAction="*")]
        System.Threading.Tasks.Task SaveAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployee", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees.GetEmployeeRequestBody Body;
        
        public GetEmployeeRequest() {
        }
        
        public GetEmployeeRequest(Employees.Employees.GetEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int i;
        
        public GetEmployeeRequestBody() {
        }
        
        public GetEmployeeRequestBody(int i) {
            this.i = i;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees.GetEmployeeResponseBody Body;
        
        public GetEmployeeResponse() {
        }
        
        public GetEmployeeResponse(Employees.Employees.GetEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Employees.Employees.Employee GetEmployeeResult;
        
        public GetEmployeeResponseBody() {
        }
        
        public GetEmployeeResponseBody(Employees.Employees.Employee GetEmployeeResult) {
            this.GetEmployeeResult = GetEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDepartmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDepartment", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees.GetDepartmentRequestBody Body;
        
        public GetDepartmentRequest() {
        }
        
        public GetDepartmentRequest(Employees.Employees.GetDepartmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDepartmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int i;
        
        public GetDepartmentRequestBody() {
        }
        
        public GetDepartmentRequestBody(int i) {
            this.i = i;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDepartmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDepartmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees.GetDepartmentResponseBody Body;
        
        public GetDepartmentResponse() {
        }
        
        public GetDepartmentResponse(Employees.Employees.GetDepartmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDepartmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Employees.Employees.Department GetDepartmentResult;
        
        public GetDepartmentResponseBody() {
        }
        
        public GetDepartmentResponseBody(Employees.Employees.Department GetDepartmentResult) {
            this.GetDepartmentResult = GetDepartmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployees", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees.GetEmployeesRequestBody Body;
        
        public GetEmployeesRequest() {
        }
        
        public GetEmployeesRequest(Employees.Employees.GetEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeesRequestBody {
        
        public GetEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees.GetEmployeesResponseBody Body;
        
        public GetEmployeesResponse() {
        }
        
        public GetEmployeesResponse(Employees.Employees.GetEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Employees.Employees.Employee[] GetEmployeesResult;
        
        public GetEmployeesResponseBody() {
        }
        
        public GetEmployeesResponseBody(Employees.Employees.Employee[] GetEmployeesResult) {
            this.GetEmployeesResult = GetEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDepartmentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDepartments", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees.GetDepartmentsRequestBody Body;
        
        public GetDepartmentsRequest() {
        }
        
        public GetDepartmentsRequest(Employees.Employees.GetDepartmentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDepartmentsRequestBody {
        
        public GetDepartmentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDepartmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDepartmentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees.GetDepartmentsResponseBody Body;
        
        public GetDepartmentsResponse() {
        }
        
        public GetDepartmentsResponse(Employees.Employees.GetDepartmentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDepartmentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Employees.Employees.Department[] GetDepartmentsResult;
        
        public GetDepartmentsResponseBody() {
        }
        
        public GetDepartmentsResponseBody(Employees.Employees.Department[] GetDepartmentsResult) {
            this.GetDepartmentsResult = GetDepartmentsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Employees_serviceSoapChannel : Employees.Employees.Employees_serviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Employees_serviceSoapClient : System.ServiceModel.ClientBase<Employees.Employees.Employees_serviceSoap>, Employees.Employees.Employees_serviceSoap {
        
        public Employees_serviceSoapClient() {
        }
        
        public Employees_serviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Employees_serviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Employees_serviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Employees_serviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Add() {
            base.Channel.Add();
        }
        
        public System.Threading.Tasks.Task AddAsync() {
            return base.Channel.AddAsync();
        }
        
        public void Edit() {
            base.Channel.Edit();
        }
        
        public System.Threading.Tasks.Task EditAsync() {
            return base.Channel.EditAsync();
        }
        
        public void Remove() {
            base.Channel.Remove();
        }
        
        public System.Threading.Tasks.Task RemoveAsync() {
            return base.Channel.RemoveAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Employees.Employees.GetEmployeeResponse Employees.Employees.Employees_serviceSoap.GetEmployee(Employees.Employees.GetEmployeeRequest request) {
            return base.Channel.GetEmployee(request);
        }
        
        public Employees.Employees.Employee GetEmployee(int i) {
            Employees.Employees.GetEmployeeRequest inValue = new Employees.Employees.GetEmployeeRequest();
            inValue.Body = new Employees.Employees.GetEmployeeRequestBody();
            inValue.Body.i = i;
            Employees.Employees.GetEmployeeResponse retVal = ((Employees.Employees.Employees_serviceSoap)(this)).GetEmployee(inValue);
            return retVal.Body.GetEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Employees.Employees.GetEmployeeResponse> Employees.Employees.Employees_serviceSoap.GetEmployeeAsync(Employees.Employees.GetEmployeeRequest request) {
            return base.Channel.GetEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Employees.Employees.GetEmployeeResponse> GetEmployeeAsync(int i) {
            Employees.Employees.GetEmployeeRequest inValue = new Employees.Employees.GetEmployeeRequest();
            inValue.Body = new Employees.Employees.GetEmployeeRequestBody();
            inValue.Body.i = i;
            return ((Employees.Employees.Employees_serviceSoap)(this)).GetEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Employees.Employees.GetDepartmentResponse Employees.Employees.Employees_serviceSoap.GetDepartment(Employees.Employees.GetDepartmentRequest request) {
            return base.Channel.GetDepartment(request);
        }
        
        public Employees.Employees.Department GetDepartment(int i) {
            Employees.Employees.GetDepartmentRequest inValue = new Employees.Employees.GetDepartmentRequest();
            inValue.Body = new Employees.Employees.GetDepartmentRequestBody();
            inValue.Body.i = i;
            Employees.Employees.GetDepartmentResponse retVal = ((Employees.Employees.Employees_serviceSoap)(this)).GetDepartment(inValue);
            return retVal.Body.GetDepartmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Employees.Employees.GetDepartmentResponse> Employees.Employees.Employees_serviceSoap.GetDepartmentAsync(Employees.Employees.GetDepartmentRequest request) {
            return base.Channel.GetDepartmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Employees.Employees.GetDepartmentResponse> GetDepartmentAsync(int i) {
            Employees.Employees.GetDepartmentRequest inValue = new Employees.Employees.GetDepartmentRequest();
            inValue.Body = new Employees.Employees.GetDepartmentRequestBody();
            inValue.Body.i = i;
            return ((Employees.Employees.Employees_serviceSoap)(this)).GetDepartmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Employees.Employees.GetEmployeesResponse Employees.Employees.Employees_serviceSoap.GetEmployees(Employees.Employees.GetEmployeesRequest request) {
            return base.Channel.GetEmployees(request);
        }
        
        public Employees.Employees.Employee[] GetEmployees() {
            Employees.Employees.GetEmployeesRequest inValue = new Employees.Employees.GetEmployeesRequest();
            inValue.Body = new Employees.Employees.GetEmployeesRequestBody();
            Employees.Employees.GetEmployeesResponse retVal = ((Employees.Employees.Employees_serviceSoap)(this)).GetEmployees(inValue);
            return retVal.Body.GetEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Employees.Employees.GetEmployeesResponse> Employees.Employees.Employees_serviceSoap.GetEmployeesAsync(Employees.Employees.GetEmployeesRequest request) {
            return base.Channel.GetEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Employees.Employees.GetEmployeesResponse> GetEmployeesAsync() {
            Employees.Employees.GetEmployeesRequest inValue = new Employees.Employees.GetEmployeesRequest();
            inValue.Body = new Employees.Employees.GetEmployeesRequestBody();
            return ((Employees.Employees.Employees_serviceSoap)(this)).GetEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Employees.Employees.GetDepartmentsResponse Employees.Employees.Employees_serviceSoap.GetDepartments(Employees.Employees.GetDepartmentsRequest request) {
            return base.Channel.GetDepartments(request);
        }
        
        public Employees.Employees.Department[] GetDepartments() {
            Employees.Employees.GetDepartmentsRequest inValue = new Employees.Employees.GetDepartmentsRequest();
            inValue.Body = new Employees.Employees.GetDepartmentsRequestBody();
            Employees.Employees.GetDepartmentsResponse retVal = ((Employees.Employees.Employees_serviceSoap)(this)).GetDepartments(inValue);
            return retVal.Body.GetDepartmentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Employees.Employees.GetDepartmentsResponse> Employees.Employees.Employees_serviceSoap.GetDepartmentsAsync(Employees.Employees.GetDepartmentsRequest request) {
            return base.Channel.GetDepartmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Employees.Employees.GetDepartmentsResponse> GetDepartmentsAsync() {
            Employees.Employees.GetDepartmentsRequest inValue = new Employees.Employees.GetDepartmentsRequest();
            inValue.Body = new Employees.Employees.GetDepartmentsRequestBody();
            return ((Employees.Employees.Employees_serviceSoap)(this)).GetDepartmentsAsync(inValue);
        }
        
        public void Choosing() {
            base.Channel.Choosing();
        }
        
        public System.Threading.Tasks.Task ChoosingAsync() {
            return base.Channel.ChoosingAsync();
        }
        
        public void Save() {
            base.Channel.Save();
        }
        
        public System.Threading.Tasks.Task SaveAsync() {
            return base.Channel.SaveAsync();
        }
    }
}
