//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employees.Employees_server {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        private int departmentField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Name1Field;
        
        private int Id1Field;
        
        private int Department1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int department {
            get {
                return this.departmentField;
            }
            set {
                if ((this.departmentField.Equals(value) != true)) {
                    this.departmentField = value;
                    this.RaisePropertyChanged("department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Name", EmitDefaultValue=false, Order=3)]
        public string Name1 {
            get {
                return this.Name1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Name1Field, value) != true)) {
                    this.Name1Field = value;
                    this.RaisePropertyChanged("Name1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Id", IsRequired=true, Order=4)]
        public int Id1 {
            get {
                return this.Id1Field;
            }
            set {
                if ((this.Id1Field.Equals(value) != true)) {
                    this.Id1Field = value;
                    this.RaisePropertyChanged("Id1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Department", IsRequired=true, Order=5)]
        public int Department1 {
            get {
                return this.Department1Field;
            }
            set {
                if ((this.Department1Field.Equals(value) != true)) {
                    this.Department1Field = value;
                    this.RaisePropertyChanged("Department1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Department : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int IdField;
        
        private int EmpCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int EmpCount {
            get {
                return this.EmpCountField;
            }
            set {
                if ((this.EmpCountField.Equals(value) != true)) {
                    this.EmpCountField = value;
                    this.RaisePropertyChanged("EmpCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Employees_server.Employees_serviceSoap")]
    public interface Employees_serviceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем name из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        Employees.Employees_server.AddResponse Add(Employees.Employees_server.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<Employees.Employees_server.AddResponse> AddAsync(Employees.Employees_server.AddRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем item из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Employees.Employees_server.Employee))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Employees.Employees_server.Department))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Employees.Employees_server.Employee[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Employees.Employees_server.Department[]))]
        Employees.Employees_server.EditResponse Edit(Employees.Employees_server.EditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit", ReplyAction="*")]
        System.Threading.Tasks.Task<Employees.Employees_server.EditResponse> EditAsync(Employees.Employees_server.EditRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем item из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Employees.Employees_server.Employee))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Employees.Employees_server.Department))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Employees.Employees_server.Employee[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Employees.Employees_server.Department[]))]
        Employees.Employees_server.RemoveResponse Remove(Employees.Employees_server.RemoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove", ReplyAction="*")]
        System.Threading.Tasks.Task<Employees.Employees_server.RemoveResponse> RemoveAsync(Employees.Employees_server.RemoveRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetEmployeeResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployee", ReplyAction="*")]
        Employees.Employees_server.GetEmployeeResponse GetEmployee(Employees.Employees_server.GetEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<Employees.Employees_server.GetEmployeeResponse> GetEmployeeAsync(Employees.Employees_server.GetEmployeeRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetDepartmentResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartment", ReplyAction="*")]
        Employees.Employees_server.GetDepartmentResponse GetDepartment(Employees.Employees_server.GetDepartmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartment", ReplyAction="*")]
        System.Threading.Tasks.Task<Employees.Employees_server.GetDepartmentResponse> GetDepartmentAsync(Employees.Employees_server.GetDepartmentRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetEmployeesResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        Employees.Employees_server.GetEmployeesResponse GetEmployees(Employees.Employees_server.GetEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<Employees.Employees_server.GetEmployeesResponse> GetEmployeesAsync(Employees.Employees_server.GetEmployeesRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetDepartmentsResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartments", ReplyAction="*")]
        Employees.Employees_server.GetDepartmentsResponse GetDepartments(Employees.Employees_server.GetDepartmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartments", ReplyAction="*")]
        System.Threading.Tasks.Task<Employees.Employees_server.GetDepartmentsResponse> GetDepartmentsAsync(Employees.Employees_server.GetDepartmentsRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем NameByIdResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NameById", ReplyAction="*")]
        Employees.Employees_server.NameByIdResponse NameById(Employees.Employees_server.NameByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NameById", ReplyAction="*")]
        System.Threading.Tasks.Task<Employees.Employees_server.NameByIdResponse> NameByIdAsync(Employees.Employees_server.NameByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save", ReplyAction="*")]
        void Save();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save", ReplyAction="*")]
        System.Threading.Tasks.Task SaveAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees_server.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(Employees.Employees_server.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool dep;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int info;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(bool dep, string name, int info) {
            this.dep = dep;
            this.name = name;
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees_server.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(Employees.Employees_server.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddResponseBody {
        
        public AddResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Edit", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees_server.EditRequestBody Body;
        
        public EditRequest() {
        }
        
        public EditRequest(Employees.Employees_server.EditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool dep;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public object item;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int info;
        
        public EditRequestBody() {
        }
        
        public EditRequestBody(bool dep, object item, string name, int info) {
            this.dep = dep;
            this.item = item;
            this.name = name;
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditResponse", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees_server.EditResponseBody Body;
        
        public EditResponse() {
        }
        
        public EditResponse(Employees.Employees_server.EditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EditResponseBody {
        
        public EditResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Remove", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees_server.RemoveRequestBody Body;
        
        public RemoveRequest() {
        }
        
        public RemoveRequest(Employees.Employees_server.RemoveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool dep;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public object item;
        
        public RemoveRequestBody() {
        }
        
        public RemoveRequestBody(bool dep, object item) {
            this.dep = dep;
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveResponse", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees_server.RemoveResponseBody Body;
        
        public RemoveResponse() {
        }
        
        public RemoveResponse(Employees.Employees_server.RemoveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RemoveResponseBody {
        
        public RemoveResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployee", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees_server.GetEmployeeRequestBody Body;
        
        public GetEmployeeRequest() {
        }
        
        public GetEmployeeRequest(Employees.Employees_server.GetEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int i;
        
        public GetEmployeeRequestBody() {
        }
        
        public GetEmployeeRequestBody(int i) {
            this.i = i;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees_server.GetEmployeeResponseBody Body;
        
        public GetEmployeeResponse() {
        }
        
        public GetEmployeeResponse(Employees.Employees_server.GetEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Employees.Employees_server.Employee GetEmployeeResult;
        
        public GetEmployeeResponseBody() {
        }
        
        public GetEmployeeResponseBody(Employees.Employees_server.Employee GetEmployeeResult) {
            this.GetEmployeeResult = GetEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDepartmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDepartment", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees_server.GetDepartmentRequestBody Body;
        
        public GetDepartmentRequest() {
        }
        
        public GetDepartmentRequest(Employees.Employees_server.GetDepartmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDepartmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int i;
        
        public GetDepartmentRequestBody() {
        }
        
        public GetDepartmentRequestBody(int i) {
            this.i = i;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDepartmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDepartmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees_server.GetDepartmentResponseBody Body;
        
        public GetDepartmentResponse() {
        }
        
        public GetDepartmentResponse(Employees.Employees_server.GetDepartmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDepartmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Employees.Employees_server.Department GetDepartmentResult;
        
        public GetDepartmentResponseBody() {
        }
        
        public GetDepartmentResponseBody(Employees.Employees_server.Department GetDepartmentResult) {
            this.GetDepartmentResult = GetDepartmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployees", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees_server.GetEmployeesRequestBody Body;
        
        public GetEmployeesRequest() {
        }
        
        public GetEmployeesRequest(Employees.Employees_server.GetEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeesRequestBody {
        
        public GetEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees_server.GetEmployeesResponseBody Body;
        
        public GetEmployeesResponse() {
        }
        
        public GetEmployeesResponse(Employees.Employees_server.GetEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Employees.Employees_server.Employee[] GetEmployeesResult;
        
        public GetEmployeesResponseBody() {
        }
        
        public GetEmployeesResponseBody(Employees.Employees_server.Employee[] GetEmployeesResult) {
            this.GetEmployeesResult = GetEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDepartmentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDepartments", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees_server.GetDepartmentsRequestBody Body;
        
        public GetDepartmentsRequest() {
        }
        
        public GetDepartmentsRequest(Employees.Employees_server.GetDepartmentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDepartmentsRequestBody {
        
        public GetDepartmentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDepartmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDepartmentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees_server.GetDepartmentsResponseBody Body;
        
        public GetDepartmentsResponse() {
        }
        
        public GetDepartmentsResponse(Employees.Employees_server.GetDepartmentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDepartmentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Employees.Employees_server.Department[] GetDepartmentsResult;
        
        public GetDepartmentsResponseBody() {
        }
        
        public GetDepartmentsResponseBody(Employees.Employees_server.Department[] GetDepartmentsResult) {
            this.GetDepartmentsResult = GetDepartmentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NameByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NameById", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees_server.NameByIdRequestBody Body;
        
        public NameByIdRequest() {
        }
        
        public NameByIdRequest(Employees.Employees_server.NameByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NameByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public NameByIdRequestBody() {
        }
        
        public NameByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NameByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NameByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Employees.Employees_server.NameByIdResponseBody Body;
        
        public NameByIdResponse() {
        }
        
        public NameByIdResponse(Employees.Employees_server.NameByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NameByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NameByIdResult;
        
        public NameByIdResponseBody() {
        }
        
        public NameByIdResponseBody(string NameByIdResult) {
            this.NameByIdResult = NameByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Employees_serviceSoapChannel : Employees.Employees_server.Employees_serviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Employees_serviceSoapClient : System.ServiceModel.ClientBase<Employees.Employees_server.Employees_serviceSoap>, Employees.Employees_server.Employees_serviceSoap {
        
        public Employees_serviceSoapClient() {
        }
        
        public Employees_serviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Employees_serviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Employees_serviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Employees_serviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Employees.Employees_server.AddResponse Employees.Employees_server.Employees_serviceSoap.Add(Employees.Employees_server.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(bool dep, string name, int info) {
            Employees.Employees_server.AddRequest inValue = new Employees.Employees_server.AddRequest();
            inValue.Body = new Employees.Employees_server.AddRequestBody();
            inValue.Body.dep = dep;
            inValue.Body.name = name;
            inValue.Body.info = info;
            Employees.Employees_server.AddResponse retVal = ((Employees.Employees_server.Employees_serviceSoap)(this)).Add(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Employees.Employees_server.AddResponse> Employees.Employees_server.Employees_serviceSoap.AddAsync(Employees.Employees_server.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<Employees.Employees_server.AddResponse> AddAsync(bool dep, string name, int info) {
            Employees.Employees_server.AddRequest inValue = new Employees.Employees_server.AddRequest();
            inValue.Body = new Employees.Employees_server.AddRequestBody();
            inValue.Body.dep = dep;
            inValue.Body.name = name;
            inValue.Body.info = info;
            return ((Employees.Employees_server.Employees_serviceSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Employees.Employees_server.EditResponse Employees.Employees_server.Employees_serviceSoap.Edit(Employees.Employees_server.EditRequest request) {
            return base.Channel.Edit(request);
        }
        
        public void Edit(bool dep, object item, string name, int info) {
            Employees.Employees_server.EditRequest inValue = new Employees.Employees_server.EditRequest();
            inValue.Body = new Employees.Employees_server.EditRequestBody();
            inValue.Body.dep = dep;
            inValue.Body.item = item;
            inValue.Body.name = name;
            inValue.Body.info = info;
            Employees.Employees_server.EditResponse retVal = ((Employees.Employees_server.Employees_serviceSoap)(this)).Edit(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Employees.Employees_server.EditResponse> Employees.Employees_server.Employees_serviceSoap.EditAsync(Employees.Employees_server.EditRequest request) {
            return base.Channel.EditAsync(request);
        }
        
        public System.Threading.Tasks.Task<Employees.Employees_server.EditResponse> EditAsync(bool dep, object item, string name, int info) {
            Employees.Employees_server.EditRequest inValue = new Employees.Employees_server.EditRequest();
            inValue.Body = new Employees.Employees_server.EditRequestBody();
            inValue.Body.dep = dep;
            inValue.Body.item = item;
            inValue.Body.name = name;
            inValue.Body.info = info;
            return ((Employees.Employees_server.Employees_serviceSoap)(this)).EditAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Employees.Employees_server.RemoveResponse Employees.Employees_server.Employees_serviceSoap.Remove(Employees.Employees_server.RemoveRequest request) {
            return base.Channel.Remove(request);
        }
        
        public void Remove(bool dep, object item) {
            Employees.Employees_server.RemoveRequest inValue = new Employees.Employees_server.RemoveRequest();
            inValue.Body = new Employees.Employees_server.RemoveRequestBody();
            inValue.Body.dep = dep;
            inValue.Body.item = item;
            Employees.Employees_server.RemoveResponse retVal = ((Employees.Employees_server.Employees_serviceSoap)(this)).Remove(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Employees.Employees_server.RemoveResponse> Employees.Employees_server.Employees_serviceSoap.RemoveAsync(Employees.Employees_server.RemoveRequest request) {
            return base.Channel.RemoveAsync(request);
        }
        
        public System.Threading.Tasks.Task<Employees.Employees_server.RemoveResponse> RemoveAsync(bool dep, object item) {
            Employees.Employees_server.RemoveRequest inValue = new Employees.Employees_server.RemoveRequest();
            inValue.Body = new Employees.Employees_server.RemoveRequestBody();
            inValue.Body.dep = dep;
            inValue.Body.item = item;
            return ((Employees.Employees_server.Employees_serviceSoap)(this)).RemoveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Employees.Employees_server.GetEmployeeResponse Employees.Employees_server.Employees_serviceSoap.GetEmployee(Employees.Employees_server.GetEmployeeRequest request) {
            return base.Channel.GetEmployee(request);
        }
        
        public Employees.Employees_server.Employee GetEmployee(int i) {
            Employees.Employees_server.GetEmployeeRequest inValue = new Employees.Employees_server.GetEmployeeRequest();
            inValue.Body = new Employees.Employees_server.GetEmployeeRequestBody();
            inValue.Body.i = i;
            Employees.Employees_server.GetEmployeeResponse retVal = ((Employees.Employees_server.Employees_serviceSoap)(this)).GetEmployee(inValue);
            return retVal.Body.GetEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Employees.Employees_server.GetEmployeeResponse> Employees.Employees_server.Employees_serviceSoap.GetEmployeeAsync(Employees.Employees_server.GetEmployeeRequest request) {
            return base.Channel.GetEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Employees.Employees_server.GetEmployeeResponse> GetEmployeeAsync(int i) {
            Employees.Employees_server.GetEmployeeRequest inValue = new Employees.Employees_server.GetEmployeeRequest();
            inValue.Body = new Employees.Employees_server.GetEmployeeRequestBody();
            inValue.Body.i = i;
            return ((Employees.Employees_server.Employees_serviceSoap)(this)).GetEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Employees.Employees_server.GetDepartmentResponse Employees.Employees_server.Employees_serviceSoap.GetDepartment(Employees.Employees_server.GetDepartmentRequest request) {
            return base.Channel.GetDepartment(request);
        }
        
        public Employees.Employees_server.Department GetDepartment(int i) {
            Employees.Employees_server.GetDepartmentRequest inValue = new Employees.Employees_server.GetDepartmentRequest();
            inValue.Body = new Employees.Employees_server.GetDepartmentRequestBody();
            inValue.Body.i = i;
            Employees.Employees_server.GetDepartmentResponse retVal = ((Employees.Employees_server.Employees_serviceSoap)(this)).GetDepartment(inValue);
            return retVal.Body.GetDepartmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Employees.Employees_server.GetDepartmentResponse> Employees.Employees_server.Employees_serviceSoap.GetDepartmentAsync(Employees.Employees_server.GetDepartmentRequest request) {
            return base.Channel.GetDepartmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Employees.Employees_server.GetDepartmentResponse> GetDepartmentAsync(int i) {
            Employees.Employees_server.GetDepartmentRequest inValue = new Employees.Employees_server.GetDepartmentRequest();
            inValue.Body = new Employees.Employees_server.GetDepartmentRequestBody();
            inValue.Body.i = i;
            return ((Employees.Employees_server.Employees_serviceSoap)(this)).GetDepartmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Employees.Employees_server.GetEmployeesResponse Employees.Employees_server.Employees_serviceSoap.GetEmployees(Employees.Employees_server.GetEmployeesRequest request) {
            return base.Channel.GetEmployees(request);
        }
        
        public Employees.Employees_server.Employee[] GetEmployees() {
            Employees.Employees_server.GetEmployeesRequest inValue = new Employees.Employees_server.GetEmployeesRequest();
            inValue.Body = new Employees.Employees_server.GetEmployeesRequestBody();
            Employees.Employees_server.GetEmployeesResponse retVal = ((Employees.Employees_server.Employees_serviceSoap)(this)).GetEmployees(inValue);
            return retVal.Body.GetEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Employees.Employees_server.GetEmployeesResponse> Employees.Employees_server.Employees_serviceSoap.GetEmployeesAsync(Employees.Employees_server.GetEmployeesRequest request) {
            return base.Channel.GetEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Employees.Employees_server.GetEmployeesResponse> GetEmployeesAsync() {
            Employees.Employees_server.GetEmployeesRequest inValue = new Employees.Employees_server.GetEmployeesRequest();
            inValue.Body = new Employees.Employees_server.GetEmployeesRequestBody();
            return ((Employees.Employees_server.Employees_serviceSoap)(this)).GetEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Employees.Employees_server.GetDepartmentsResponse Employees.Employees_server.Employees_serviceSoap.GetDepartments(Employees.Employees_server.GetDepartmentsRequest request) {
            return base.Channel.GetDepartments(request);
        }
        
        public Employees.Employees_server.Department[] GetDepartments() {
            Employees.Employees_server.GetDepartmentsRequest inValue = new Employees.Employees_server.GetDepartmentsRequest();
            inValue.Body = new Employees.Employees_server.GetDepartmentsRequestBody();
            Employees.Employees_server.GetDepartmentsResponse retVal = ((Employees.Employees_server.Employees_serviceSoap)(this)).GetDepartments(inValue);
            return retVal.Body.GetDepartmentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Employees.Employees_server.GetDepartmentsResponse> Employees.Employees_server.Employees_serviceSoap.GetDepartmentsAsync(Employees.Employees_server.GetDepartmentsRequest request) {
            return base.Channel.GetDepartmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Employees.Employees_server.GetDepartmentsResponse> GetDepartmentsAsync() {
            Employees.Employees_server.GetDepartmentsRequest inValue = new Employees.Employees_server.GetDepartmentsRequest();
            inValue.Body = new Employees.Employees_server.GetDepartmentsRequestBody();
            return ((Employees.Employees_server.Employees_serviceSoap)(this)).GetDepartmentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Employees.Employees_server.NameByIdResponse Employees.Employees_server.Employees_serviceSoap.NameById(Employees.Employees_server.NameByIdRequest request) {
            return base.Channel.NameById(request);
        }
        
        public string NameById(int id) {
            Employees.Employees_server.NameByIdRequest inValue = new Employees.Employees_server.NameByIdRequest();
            inValue.Body = new Employees.Employees_server.NameByIdRequestBody();
            inValue.Body.id = id;
            Employees.Employees_server.NameByIdResponse retVal = ((Employees.Employees_server.Employees_serviceSoap)(this)).NameById(inValue);
            return retVal.Body.NameByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Employees.Employees_server.NameByIdResponse> Employees.Employees_server.Employees_serviceSoap.NameByIdAsync(Employees.Employees_server.NameByIdRequest request) {
            return base.Channel.NameByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Employees.Employees_server.NameByIdResponse> NameByIdAsync(int id) {
            Employees.Employees_server.NameByIdRequest inValue = new Employees.Employees_server.NameByIdRequest();
            inValue.Body = new Employees.Employees_server.NameByIdRequestBody();
            inValue.Body.id = id;
            return ((Employees.Employees_server.Employees_serviceSoap)(this)).NameByIdAsync(inValue);
        }
        
        public void Save() {
            base.Channel.Save();
        }
        
        public System.Threading.Tasks.Task SaveAsync() {
            return base.Channel.SaveAsync();
        }
    }
}
